sonar.projectKey=Seo251_OOAD
sonar.organization=seo251

sonar.sources=src
sonar.tests=tests

sonar.cfamily.gcov.reportsPath=build

sonar.cfamily.compile-commands=bw-output/compile_commands.json
#sonar.cfamily.build-wrapper-output=bw-output