sonar.projectKey=Seo251_OOAD
sonar.organization=seo251

sonar.sources=src
sonar.tests=tests
sonar.cfamily.compile-commands=build/compile_commands.json

# 추가할 옵션 (경로 불일치 해결용)
sonar.cfamily.build-wrapper-output.bypass=true
sonar.sources=src