sonar.projectKey=Jungsunmin_OOAD_TeamProj
sonar.organization=konkukooad

sonar.sources=src
sonar.tests=tests
sonar.cfamily.compile-commands=build/compile_commands.json

sonar.cpp.lcov.reportPath=coverage.info	
sonar.cppcheck.reportPath=cppcheck-report.xml	
sonar.clangtidy.reportPath=clang-tidy-report.txt